import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'pl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    shop: 'Shop',
    collections: 'Collections',
    about: 'About',
    contact: 'Contact',
    cart: 'Cart',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    adminDashboard: 'Admin Dashboard',

    // Product
    addToCart: 'Add to Cart',
    price: 'Price',
    size: 'Size',
    weight: 'Weight',
    category: 'Category',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    viewProduct: 'View Product',
    featuredCollection: 'Featured Collection',
    featuredCollectionDescription: 'Discover our most beloved luxury soy candles, each inspired by iconic fragrances and crafted with the finest natural ingredients.',
    exploreFullCollection: 'Explore Full Collection',

    // Cart
    shoppingCart: 'Shopping Cart',
    emptyCart: 'Your cart is empty',
    addSomeCandles: 'Add some candles to get started',
    browseCollection: 'Browse Collection',
    subtotal: 'Subtotal',
    total: 'Total',
    checkoutNow: 'Checkout Now',
    viewFullCart: 'View Full Cart',
    items: 'items',
    clearCart: 'Clear Cart',
    continueShopping: 'Continue Shopping',
    shipping: 'Shipping',
    freeShipping: 'Free',
    remove: 'Remove',

    // Forms
    email: 'Email',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',

    // Hero Section
    heroTitle: 'Spirit of Candles',
    heroSubtitle: 'Illuminate your soul with luxury scented candles',
    shopNow: 'Shop Now',
    exploreCollection: 'Explore Collection',

    // Categories
    luxury: 'Luxury',
    nature: 'Nature',
    fresh: 'Fresh',

    // Footer
    quickLinks: 'Quick Links',
    customerService: 'Customer Service',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved',

    // Search
    search: 'Search',
    searchPlaceholder: 'Search products...',
    searchResults: 'Search Results',
    noResults: 'No products found',

    // Contact
    contactUs: 'Contact Us',
    name: 'Name',
    message: 'Message',
    sendMessage: 'Send Message',
    subject: 'Subject',
    getInTouch: 'Get In Touch',
    sendUsAMessage: 'Send Us A Message',
    contactInformation: 'Contact Information',
    emailUs: 'Email Us',
    callUs: 'Call Us',
    visitUs: 'Visit Us',
    responseTime: 'Response Time',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    viewAllFaqs: 'View All FAQs',
    customerServiceHours: 'Customer Service Hours',
    emailSupport: 'Email Support',
    phoneSupport: 'Phone Support',

    // Dashboard additions
    revenue: 'Revenue',
    manageProductInventory: 'Manage your product inventory',
    addNewProduct: 'Add New Product',
    editProductTitle: 'Edit Product',
    updateProduct: 'Update Product',
    createProduct: 'Create Product',
    deleteConfirm: 'Are you sure you want to delete this product?',
    billing: 'Billing',
    status: 'Status',
    customerDetails: 'Customer Details',
    viewDetails: 'View Details',
    exportData: 'Export Data',
    statistics: 'Statistics',

    // Form labels
    nameEn: 'Name (EN)',
    namePl: 'Name (PL)',
    descriptionEn: 'Description (EN)',
    descriptionPl: 'Description (PL)',
    pricePln: 'Price PLN (cents)',
    priceEur: 'Price EUR (cents)',

    // Animations and UI
    materializing: 'Materializing',
    shopCollection: 'Shop Collection',
    learnOurStory: 'Learn Our Story',
    rebornYourNature: 'Reborn Your Nature',

    // Admin
    productManagement: 'Product Management',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productName: 'Product Name',
    productDescription: 'Product Description',
    productImage: 'Product Image',
    uploadImage: 'Upload Image',
    selectImage: 'Select Image',
    imageUploaded: 'Image uploaded successfully',
    productPrice: 'Product Price',
    productCategory: 'Product Category',
    productSize: 'Product Size',
    productWeight: 'Product Weight (Optional)',
    stockQuantity: 'Stock Quantity',
    imageUrl: 'Image URL',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    optional: 'Optional',
    products: 'Products',
    orders: 'Orders',
    customers: 'Customers',
    settings: 'Settings',

    // User Dashboard
    profile: 'Profile',
    accountStatus: 'Account Status',
    spiritMembers: 'Spirit Members',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    orderHistory: 'Order History',
    noOrders: 'No orders found',
    language: 'Language',
    preferredLanguage: 'Preferred Language',

    // Shipping and Checkout
    shippingAddress: 'Shipping Address',
    deliveryAddress: 'Delivery Address',
    changeAddress: 'Change Address',
    shippingOptions: 'Shipping Options',
    standardDelivery: 'Standard Delivery',
    net: 'net',
    selectedShipping: 'Selected Shipping',
    confirmAndProceed: 'Confirm and Proceed to Payment',
    calculatedNext: 'Calculated next',
    orderItems: 'Order Items',
    fullName: 'Full Name',
    streetAddress: 'Street Address',
    streetNumber: 'Street Number',
    apartmentNumber: 'Apartment Number (Optional)',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    phone: 'Phone',
    phonePrefix: "Prefix",
    phoneNumber: "Phone Number",
    phonePrefixHint: "Telephone prefix (include '+', e.g., +48)",
    calculating: 'Calculating...',
    calculateShipping: 'Calculate Shipping Options',
    shippingCalculationError: 'Failed to calculate shipping options. Please try again.',

    // Common UI elements
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    addedToCart: 'Added to cart',
    itemAdded: 'Item added to cart',
    proceedToCheckout: 'Proceed to checkout',
    checkout: 'Checkout',
    paymentSuccess: 'Payment successful',
    orderPlaced: 'Order placed',
    thankYou: 'Thank you',
    orderNumber: 'Order number',
    accessDenied: 'Access denied',
    noPermission: 'You don\'t have permission to access this page',
    clear: 'Clear',
    notProvided: 'Not provided',
    notSet: 'Not set',
    memberSince: 'Member since',
    username: 'Username',
    loginRequired: 'Login Required',
    loginToCheckout: 'You need to log in to complete your purchase',
    proceedToPayment: 'Proceed to Payment',
    backToCart: 'Back to Cart',
    processing: 'Processing...',
    orderSummary: 'Order Summary',

    // Contact page specifics
    missingInformation: 'Missing Information',
    pleaseFillRequired: 'Please fill in all required fields.',
    messageSentSuccessfully: 'Message Sent Successfully!',
    thankYouContact: 'Thank you for contacting us. We\'ll get back to you within 24-48 hours.',
    errorSendingMessage: 'Failed to send message. Please try again or contact us directly.',
    yourFullName: 'Your full name',
    yourEmail: 'your@email.com',
    whatsThisAbout: 'What\'s this about?',
    tellUsHowWeCanHelp: 'Tell us how we can help you...',
    howLongBurn: 'How long do your candles burn?',
    burnTimeAnswer: 'Our 180g candles burn for approximately 45-50 hours.',
    areEcoFriendly: 'Are your candles eco-friendly?',
    ecoAnswer: 'Yes! We use 100% natural soy wax, wooden wicks, and recyclable glass containers. Our candles are vegan and cruelty-free.',
    shipInternationally: 'Do you ship internationally?',
    shippingAnswer: 'Currently, we ship within Poland and to select EU countries. Contact us for specific shipping information.',
    responseTime24: '24/7 - We respond within 24-48 hours',
    phoneHours: 'Monday - Friday: 9:00 AM - 6:00 PM CET',

    // About page
    discoverOurCollection: 'Discover Our Collection',
    whyChooseSpiritCandles: 'Why Choose SPIRIT CANDLES',
    naturalSoyWax: '100% Natural Soy Wax',
    naturalSoyWaxDesc: 'Crafted from pure soy wax for a clean, eco-friendly burn that lasts longer than traditional paraffin candles.',
    woodenWicks: 'Wooden Wicks',
    woodenWicksDesc: 'Our crackling wooden wicks create an authentic fireplace ambiance while providing an even, consistent flame.',
    handPouredWithLove: 'Hand-Poured with Love',
    handPouredDesc: 'Each candle is carefully hand-poured in small batches to ensure the highest quality and attention to detail.',
    luxuryFragrances: 'Luxury Fragrances',
    luxuryFragrancesDesc: 'Inspired by iconic perfumes, our scents are complex, sophisticated, and designed to transform any space.',
    ourStory: 'Our Story',
    legalDisclaimer: 'Legal Disclaimer:',

    // Shop page
    ourCollection: 'Our Collection',
    discoverCompleteRange: 'Discover our complete range of luxury soy candles, each inspired by iconic fragrances and handcrafted with natural ingredients.',
    searchCandles: 'Search candles...',
    filterBy: 'Filter by',
    sortBy: 'Sort by',
    allProducts: 'All Products',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    featured: 'Featured',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    nameAToZ: 'Name: A to Z',
    product: 'product',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your search or filter criteria',
    clearFilters: 'Clear Filters',
    loadMoreProducts: 'Load More Products',

    // Collections page
    ourCollections: 'Our Collections',
    discoverCuratedCollections: 'Discover carefully curated collections of luxury soy candles, each designed to create the perfect ambiance for every moment and mood.',
    luxuryCollection: 'Luxury Collection',
    luxuryCollectionDesc: 'Premium fragrances inspired by the world\'s most exclusive perfumes',
    freshAndClean: 'Fresh & Clean',
    freshDesc: 'Light, airy scents that refresh and energize your space',
    romanticEvening: 'Romantic Evening',
    romanticDesc: 'Intimate, warm fragrances perfect for special moments',
    bestSellers: 'Best Sellers',
    bestSellersDesc: 'Our most loved candles chosen by customers worldwide',
    exploreCollectionPage: 'Explore Collection',
    backToAllCollections: '← Back to All Collections',
    moreProductsComingSoon: 'More products coming soon to this collection...',
    cantDecide: 'Can\'t decide? Browse all our candles',
    shopAllCandles: 'Shop All Candles',

    // Product Detail page
    backToShop: 'Back to Shop',
    productNotFound: 'Product not found',
    returnToShop: 'Return to Shop',
    inspiredBy: 'Inspired by',
    reviews: 'reviews',
    buyNow: 'Buy Now',
    wishlist: 'Wishlist',
    share: 'Share',
    moodAndAmbiance: 'Mood & Ambiance',
    productDetails: 'Product Details',
    waxType: 'Wax Type',
    wick: 'Wick',
    handPoured: 'Hand Poured',
    burnTime: 'Burn Time',
    naturalIngredients: 'Natural Ingredients',
    careInstructions: 'Care Instructions',
    inspirationNotice: 'Inspiration Notice:',
    fragranceReferences: 'Fragrance references are inspirations only. SPIRIT CANDLES is not affiliated with or endorsed by the original trademark owners.',

    // Payment Success page
    paymentSuccessful: 'Payment Successful!',
    orderConfirmation: 'Thank you for your purchase! Your order has been confirmed.',
    sessionId: 'Session ID',
    viewOrders: 'View My Orders',
    emailConfirmation: 'A confirmation email will be sent to you shortly.',
    
    addedToWishlist: 'Added to Wishlist',
    removedFromWishlist: 'Removed from Wishlist',
    myWishlist: 'My Wishlist',
    emptyWishlist: 'Your wishlist is empty',
    startAddingFavorites: 'Start adding your favorite products',
    item: 'item',

    // Reviews
    customerReviews: 'Customer Reviews',
    noReviewsYet: 'No reviews yet',
    basedOnReviews: 'Based on {count} reviews',
    writeReview: 'Write a Review',
    editReview: 'Edit Review',
    yourRating: 'Your Rating',
    yourReview: 'Your Review',
    shareYourThoughts: 'Share your thoughts...',
    submitReview: 'Submit Review',
    updateReview: 'Update Review',
    allReviews: 'All Reviews',

    // Order statuses
    paid: 'Paid',
    awaitingApproval: 'Awaiting Approval',
    readyToShip: 'Ready to Ship',
    inTransit: 'In Transit',
    delivered: 'Delivered',
    completed: 'Completed',
    
    // Billing
    paymentHistory: 'Payment History',
    billingDescription: 'All payments are processed securely through Stripe. Your payment history is linked to your orders.',
    viewOrdersForPayments: 'View the Orders tab to see your complete payment history.',

    // Shipment modal
    shipmentConfirmation: 'Shipment Confirmation',
    orderInformation: 'Order Information',
    shipmentDetails: 'Shipment Details',
    carrier: 'Carrier',
    serviceId: 'Service ID',
    enableEditingDimensions: 'Enable editing dimensions and weight',
    width: 'Width',
    height: 'Height',
    length: 'Length',
    confirmAndCreateShipment: 'Confirm and Create Shipment',
    
    // Warehouse Management
    actions: 'Actions',
    editProductDetails: 'Edit',
    viewProductPage: 'View',
    warehouse: 'Warehouse',
    warehouseManagement: 'Warehouse Management',
    stockOverview: 'Stock Overview',
    productStockLevels: 'Product Stock Levels',
    totalItems: 'Total Items',
    lowStockAlerts: 'Low Stock Alerts',
    updateStock: 'Update Stock',
    published: 'Published',
    unpublished: 'Unpublished',
  },
  pl: {
    // Navigation
    home: 'Strona główna',
    shop: 'Sklep',
    collections: 'Kolekcje',
    about: 'O nas',
    contact: 'Kontakt',
    cart: 'Koszyk',
    login: 'Zaloguj',
    register: 'Rejestracja',
    logout: 'Wyloguj',
    dashboard: 'Panel',
    adminDashboard: 'Panel administratora',

    // Product
    addToCart: 'Dodaj do koszyka',
    price: 'Cena',
    size: 'Rozmiar',
    weight: 'Waga',
    category: 'Kategoria',
    inStock: 'Dostępny',
    outOfStock: 'Wyprzedany',
    quantity: 'Ilość',
    viewProduct: 'Zobacz produkt',
    featuredCollection: 'Kolekcja wyróżniona',
    featuredCollectionDescription: 'Odkryj nasze najbardziej ukochane luksusowe świece sojowe, każda inspirowana kultowymi zapachami i stworzona z najlepszych naturalnych składników.',
    exploreFullCollection: 'Poznaj pełną kolekcję',

    // Cart
    shoppingCart: 'Koszyk zakupów',
    emptyCart: 'Twój koszyk jest pusty',
    addSomeCandles: 'Dodaj świece aby rozpocząć',
    browseCollection: 'Przeglądaj kolekcję',
    subtotal: 'Suma częściowa',
    total: 'Razem',
    checkoutNow: 'Zamów teraz',
    viewFullCart: 'Zobacz pełny koszyk',
    items: 'przedmiotów',
    clearCart: 'Wyczyść koszyk',
    continueShopping: 'Kontynuuj zakupy',
    shipping: 'Dostawa',
    freeShipping: 'Darmowa',
    remove: 'Usuń',

    // Forms
    email: 'Email',
    password: 'Hasło',
    firstName: 'Imię',
    lastName: 'Nazwisko',
    confirmPassword: 'Potwierdź hasło',
    signIn: 'Zaloguj się',
    signUp: 'Zarejestruj się',
    dontHaveAccount: 'Nie masz konta?',
    alreadyHaveAccount: 'Masz już konto?',
    changePassword: 'Zmień hasło',
    currentPassword: 'Obecne hasło',
    newPassword: 'Nowe hasło',
    confirmNewPassword: 'Potwierdź nowe hasło',

    // Hero Section
    heroTitle: 'Duch Świec',
    heroSubtitle: 'Oświetl swoją duszę luksusowymi świecami zapachowymi',
    shopNow: 'Kup teraz',
    exploreCollection: 'Poznaj pełną kolekcję',

    // Categories
    luxury: 'Luksus',
    nature: 'Natura',
    fresh: 'Świeżość',

    // Footer
    quickLinks: 'Szybkie linki',
    customerService: 'Obsługa klienta',
    followUs: 'Śledź nas',
    allRightsReserved: 'Wszelkie prawa zastrzeżone',

    // Search
    search: 'Szukaj',
    searchPlaceholder: 'Szukaj produktów...',
    searchResults: 'Wyniki wyszukiwania',
    noResults: 'Nie znaleziono produktów',

    // Contact
    contactUs: 'Skontaktuj się z nami',
    name: 'Imię',
    message: 'Wiadomość',
    sendMessage: 'Wyślij wiadomość',
    subject: 'Temat',
    getInTouch: 'Skontaktuj się z nami',
    sendUsAMessage: 'Wyślij nam wiadomość',
    contactInformation: 'Informacje kontaktowe',
    emailUs: 'Napisz do nas',
    callUs: 'Zadzwoń',
    visitUs: 'Odwiedź nas',
    responseTime: 'Czas odpowiedzi',
    frequentlyAskedQuestions: 'Często zadawane pytania',
    viewAllFaqs: 'Zobacz wszystkie FAQ',
    customerServiceHours: 'Godziny obsługi klienta',
    emailSupport: 'Wsparcie email',
    phoneSupport: 'Wsparcie telefoniczne',

    // Dashboard additions
    revenue: 'Przychody',
    manageProductInventory: 'Zarządzaj swoim asortymentem',
    addNewProduct: 'Dodaj nowy produkt',
    editProductTitle: 'Edytuj produkt',
    updateProduct: 'Zaktualizuj produkt',
    createProduct: 'Utwórz produkt',
    deleteConfirm: 'Czy na pewno chcesz usunąć ten produkt?',
    billing: 'Płatności',
    status: 'Status',
    customerDetails: 'Szczegóły klienta',
    viewDetails: 'Zobacz szczegóły',
    exportData: 'Eksportuj dane',
    statistics: 'Statystyki',

    // Form labels
    nameEn: 'Nazwa (EN)',
    namePl: 'Nazwa (PL)',
    descriptionEn: 'Opis (EN)',
    descriptionPl: 'Opis (PL)',
    pricePln: 'Cena PLN (grosze)',
    priceEur: 'Cena EUR (centy)',

    // Animations and UI
    materializing: 'Materializuje się',
    shopCollection: 'Kup kolekcję',
    learnOurStory: 'Poznaj naszą historię',
    rebornYourNature: 'Odrodzenie twojej natury',

    // Admin
    productManagement: 'Zarządzanie produktami',
    addProduct: 'Dodaj produkt',
    editProduct: 'Edytuj produkt',
    deleteProduct: 'Usuń produkt',
    productName: 'Nazwa produktu',
    productDescription: 'Opis produktu',
    productImage: 'Zdjęcie produktu',
    uploadImage: 'Wgraj zdjęcie',
    selectImage: 'Wybierz zdjęcie',
    imageUploaded: 'Zdjęcie wgrane pomyślnie',
    productPrice: 'Cena produktu',
    productCategory: 'Kategoria produktu',
    productSize: 'Rozmiar produktu',
    productWeight: 'Waga produktu (opcjonalnie)',
    stockQuantity: 'Stan magazynowy',
    imageUrl: 'URL obrazu',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    optional: 'Opcjonalne',
    products: 'Produkty',
    orders: 'Zamówienia',
    customers: 'Klienci',
    settings: 'Ustawienia',

    // User Dashboard
    profile: 'Profil',
    accountStatus: 'Status konta',
    spiritMembers: 'Członkowie Spirit',
    editProfile: 'Edytuj profil',
    saveChanges: 'Zapisz zmiany',
    orderHistory: 'Historia zamówień',
    noOrders: 'Nie znaleziono zamówień',
    language: 'Język',
    preferredLanguage: 'Preferowany język',

    // Shipping and Checkout
    shippingAddress: 'Adres wysyłki',
    deliveryAddress: 'Adres dostawy',
    changeAddress: 'Zmień adres',
    shippingOptions: 'Opcje wysyłki',
    standardDelivery: 'Dostawa standardowa',
    net: 'netto',
    selectedShipping: 'Wybrana wysyłka',
    confirmAndProceed: 'Potwierdź i przejdź do płatności',
    calculatedNext: 'Obliczone dalej',
    orderItems: 'Pozycje zamówienia',
    fullName: 'Imię i nazwisko',
    streetAddress: 'Adres ulicy',
    streetNumber: 'Numer domu',
    apartmentNumber: 'Numer mieszkania (opcjonalnie)',
    city: 'Miasto',
    postalCode: 'Kod pocztowy',
    country: 'Kraj',
    phone: 'Telefon',
    phonePrefix: 'Prefiks',
    phoneNumber: 'Numer telefonu',
    phonePrefixHint: "Prefiks telefonu (wpisz '+', np. +48)",
    calculating: 'Obliczanie...',
    calculateShipping: 'Oblicz opcje wysyłki',
    shippingCalculationError: 'Nie udało się obliczyć opcji wysyłki. Spróbuj ponownie.',

    // Common UI elements
    loading: 'Ładowanie...',
    error: 'Błąd',
    success: 'Sukces',
    confirm: 'Potwierdź',
    yes: 'Tak',
    no: 'Nie',
    close: 'Zamknij',
    back: 'Wstecz',
    next: 'Dalej',
    previous: 'Poprzedni',
    addedToCart: 'Dodano do koszyka',
    itemAdded: 'Przedmiot dodany do koszyka',
    proceedToCheckout: 'Przejdź do kasy',
    checkout: 'Kasa',
    paymentSuccess: 'Płatność pomyślna',
    orderPlaced: 'Zamówienie złożone',
    thankYou: 'Dziękujemy',
    orderNumber: 'Numer zamówienia',
    accessDenied: 'Dostęp zabroniony',
    noPermission: 'Nie masz uprawnień do tej strony',
    clear: 'Wyczyść',
    notProvided: 'Nie podano',
    notSet: 'Nie ustawiono',
    memberSince: 'Członek od',
    username: 'Nazwa użytkownika',
    loginRequired: 'Wymagane logowanie',
    loginToCheckout: 'Musisz się zalogować, aby dokończyć zakup',
    proceedToPayment: 'Przejdź do płatności',
    backToCart: 'Wróć do koszyka',
    processing: 'Przetwarzanie...',
    orderSummary: 'Podsumowanie zamówienia',

    // Contact page specifics
    missingInformation: 'Brakuje informacji',
    pleaseFillRequired: 'Wypełnij wszystkie wymagane pola.',
    messageSentSuccessfully: 'Wiadomość wysłana pomyślnie!',
    thankYouContact: 'Dziękujemy za kontakt. Odpowiemy w ciągu 24-48 godzin.',
    errorSendingMessage: 'Nie udało się wysłać wiadomości. Spróbuj ponownie lub skontaktuj się bezpośrednio.',
    yourFullName: 'Twoje pełne imię i nazwisko',
    yourEmail: 'twoj@email.com',
    whatsThisAbout: 'O co chodzi?',
    tellUsHowWeCanHelp: 'Powiedz nam, jak możemy Ci pomóc...',
    howLongBurn: 'Jak długo palą się Wasze świece?',
    burnTimeAnswer: 'Nasze świece 180g palą się około 45-50 godzin.',
    areEcoFriendly: 'Czy Wasze świece są ekologiczne?',
    ecoAnswer: 'Tak! Używamy 100% naturalnego wosku sojowego, drewnianych knotów i szklanych pojemników nadających się do recyklingu. Nasze świece są wegańskie i nie testowane na zwierzętach.',
    shipInternationally: 'Czy wysyłacie międzynarodowo?',
    shippingAnswer: 'Obecnie wysyłamy w Polsce i do wybranych krajów UE. Skontaktuj się z nami w sprawie szczegółowych informacji o wysyłce.',
    responseTime24: '24/7 - Odpowiadamy w ciągu 24-48 godzin',
    phoneHours: 'Poniedziałek - Piątek: 9:00 - 18:00 CET',

    // About page
    discoverOurCollection: 'Odkryj naszą kolekcję',
    whyChooseSpiritCandles: 'Dlaczego wybrać SPIRIT CANDLES',
    naturalSoyWax: '100% naturalny wosk sojowy',
    naturalSoyWaxDesc: 'Wykonane z czystego wosku sojowego dla czystego, ekologicznego spalania, które trwa dłużej niż tradycyjne świece parafinowe.',
    woodenWicks: 'Drewniane knoty',
    woodenWicksDesc: 'Nasze trzaskające drewniane knoty tworzą autentyczną atmosferę kominka, zapewniając równy, stały płomień.',
    handPouredWithLove: 'Ręcznie odlewane z miłością',
    handPouredDesc: 'Każda świeca jest starannie odlewana ręcznie w małych partiach, aby zapewnić najwyższą jakość i dbałość o szczegóły.',
    luxuryFragrances: 'Luksusowe zapachy',
    luxuryFragrancesDesc: 'Inspirowane kultowymi perfumami, nasze zapachy są złożone, wyrafinowane i zaprojektowane do transformacji każdej przestrzeni.',
    ourStory: 'Nasza historia',
    legalDisclaimer: 'Zastrzeżenie prawne:',

    // Shop page
    ourCollection: 'Nasza kolekcja',
    discoverCompleteRange: 'Odkryj nasz kompletny asortyment luksusowych świec sojowych, każda inspirowana kultowymi zapachami i wykonana ręcznie z naturalnych składników.',
    searchCandles: 'Szukaj świec...',
    filterBy: 'Filtruj według',
    sortBy: 'Sortuj według',
    allProducts: 'Wszystkie produkty',
    newArrivals: 'Nowości',
    bestsellers: 'Bestsellery',
    featured: 'Polecane',
    priceLowToHigh: 'Cena: Od najniższej',
    priceHighToLow: 'Cena: Od najwyższej',
    nameAToZ: 'Nazwa: A do Z',
    product: 'produkt',
    noProductsFound: 'Nie znaleziono produktów',
    tryAdjustingFilters: 'Spróbuj dostosować kryteria wyszukiwania lub filtrów',
    clearFilters: 'Wyczyść filtry',
    loadMoreProducts: 'Załaduj więcej produktów',

    // Collections page
    ourCollections: 'Nasze kolekcje',
    discoverCuratedCollections: 'Odkryj starannie wyselekcjonowane kolekcje luksusowych świec sojowych, każda zaprojektowana, aby stworzyć idealną atmosferę na każdą chwilę i nastrój.',
    luxuryCollection: 'Kolekcja luksusowa',
    luxuryCollectionDesc: 'Luksusowe zapachy inspirowane najbardziej ekskluzywnymi perfumami świata',
    freshAndClean: 'Świeże i czyste',
    freshDesc: 'Lekkie, przewiewne zapachy, które odświeżają i dodają energii Twojej przestrzeni',
    romanticEvening: 'Romantyczny wieczór',
    romanticDesc: 'Intymne, ciepłe zapachy idealne na wyjątkowe chwile',
    bestSellers: 'Bestsellery',
    bestSellersDesc: 'Nasze najbardziej lubiane świece wybrane przez klientów z całego świata',
    exploreCollectionPage: 'Poznaj kolekcję',
    backToAllCollections: '← Wróć do wszystkich kolekcji',
    moreProductsComingSoon: 'Więcej produktów wkrótce w tej kolekcji...',
    cantDecide: 'Nie możesz się zdecydować? Przeglądaj wszystkie nasze świece',
    shopAllCandles: 'Kup wszystkie świece',

    // Product Detail page
    backToShop: 'Wróć do sklepu',
    productNotFound: 'Produkt nie znaleziony',
    returnToShop: 'Wróć do sklepu',
    inspiredBy: 'Inspirowane przez',
    reviews: 'opinii',
    buyNow: 'Kup teraz',
    wishlist: 'Lista życzeń',
    share: 'Udostępnij',
    moodAndAmbiance: 'Nastrój i atmosfera',
    productDetails: 'Szczegóły produktu',
    waxType: 'Typ wosku',
    wick: 'Knot',
    handPoured: 'Odlewane ręcznie',
    burnTime: 'Czas spalania',
    naturalIngredients: 'Naturalne składniki',
    careInstructions: 'Instrukcje pielęgnacji',
    inspirationNotice: 'Uwaga o inspiracji:',
    fragranceReferences: 'Odniesienia do zapachów to tylko inspiracje. SPIRIT CANDLES nie jest powiązane ani popierane przez pierwotnych właścicieli znaków towarowych.',

    // Payment Success page
    paymentSuccessful: 'Płatność pomyślna!',
    orderConfirmation: 'Dziękujemy za zakup! Twoje zamówienie zostało potwierdzone.',
    sessionId: 'ID sesji',
    viewOrders: 'Zobacz moje zamówienia',
    emailConfirmation: 'Wkrótce otrzymasz e-mail z potwierdzeniem.',
    
    addedToWishlist: 'Dodano do listy życzeń',
    removedFromWishlist: 'Usunięto z listy życzeń',
    myWishlist: 'Moja lista życzeń',
    emptyWishlist: 'Twoja lista życzeń jest pusta',
    startAddingFavorites: 'Zacznij dodawać ulubione produkty',
    item: 'przedmiot',

    // Reviews
    customerReviews: 'Opinie klientów',
    noReviewsYet: 'Brak opinii',
    basedOnReviews: 'Na podstawie {count} opinii',
    writeReview: 'Napisz opinię',
    editReview: 'Edytuj opinię',
    yourRating: 'Twoja ocena',
    yourReview: 'Twoja opinia',
    shareYourThoughts: 'Podziel się swoimi przemyśleniami...',
    submitReview: 'Wyślij opinię',
    updateReview: 'Zaktualizuj opinię',
    allReviews: 'Wszystkie opinie',

    // Order statuses
    paid: 'Opłacone',
    awaitingApproval: 'Oczekuje na zatwierdzenie',
    readyToShip: 'Gotowe do wysyłki',
    inTransit: 'W drodze',
    delivered: 'Dostarczone',
    completed: 'Zakończone',
    
    // Billing
    paymentHistory: 'Historia płatności',
    billingDescription: 'Wszystkie płatności są przetwarzane bezpiecznie przez Stripe. Twoja historia płatności jest powiązana z zamówieniami.',
    viewOrdersForPayments: 'Zobacz kartę Zamówienia, aby zobaczyć pełną historię płatności.',

    // Shipment modal
    shipmentConfirmation: 'Potwierdzenie wysyłki',
    orderInformation: 'Informacje o zamówieniu',
    shipmentDetails: 'Szczegóły wysyłki',
    carrier: 'Kurier',
    serviceId: 'ID usługi',
    enableEditingDimensions: 'Włącz edycję wymiarów i wagi',
    width: 'Szerokość',
    height: 'Wysokość',
    length: 'Długość',
    confirmAndCreateShipment: 'Potwierdź i utwórz przesyłkę',
    
    // Warehouse Management
    actions: 'Akcje',
    editProductDetails: 'Edytuj',
    viewProductPage: 'Zobacz',
    warehouse: 'Magazyn',
    warehouseManagement: 'Zarządzanie Magazynem',
    stockOverview: 'Przegląd Zapasów',
    productStockLevels: 'Poziomy Zapasów Produktów',
    totalItems: 'Przedmioty Ogółem',
    lowStockAlerts: 'Niski Stan',
    updateStock: 'Aktualizuj Stan',
    published: 'Opublikowany',
    unpublished: 'Nieopublikowany',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};